### ISSUE TITLE
Encoding problem

### ISSUE THREAD

**Issue by MichalMed** [inspire-eu-validation/ets-repository#93]
During the test of WFS direct access http://inspire-sandbox.jrc.ec.europa.eu/etf-webapp/v2/TestRuns/EID18b3511c-0afc-4bd2-a82b-7e58bb809e21.html I've got an errror message, that:

> OGC TEAM Engine returned HTTP status code: 500 (Internal Server Error). Message: Error executing test suite (wfs20-1.26)
>    Please note: it seems that your server does not support URL encoding correctly. The encoded URL 'http://services.cuzk.cz/wfs/inspire-cp-wfs.asp?ACCEPTVERSIONS=2.0.0%26REQUEST=GetCapabilities%26SERVICE=wfs%26VERSION=2.0.0' and the URL 'http://services.cuzk.cz/wfs/inspire-cp-wfs.asp?ACCEPTVERSIONS=2.0.0&REQUEST=GetCapabilities&SERVICE=wfs&VERSION=2.0.0' return different documents. The OGC TEAM engine uses only the encoded URL.

This looks weird, because if UrlEncode is used, the whole request shall loook like this:    http%3A%2F%2Fservices.cuzk.cz%2Fwfs%2Finspire-cp-wfs.asp%3FACCEPTVERSIONS%3D2.0.0%26request%3DGetCapabilities%26service%3Dwfs%26VERSION%3D2.0.0
Why do you want to have encoded only '&' and not the whole URI?

**Comment by jonherrmann** [comment]
The query needs to be encoded for the OGC Team Engine, see the description of the WFS parameter here: http://cite.opengeospatial.org/teamengine/rest/suites/wfs20/1.26/

With your service it works, when the complete query part is encoded:
http://services.cuzk.cz/wfs/inspire-cp-wfs.asp%3FACCEPTVERSIONS%3D2.0.0%26REQUEST%3DGetCapabilities%26SERVICE%3Dwfs%26VERSION%3D2.0.0

However if we pass the complete query encoded URL to the OGC Team Engine, we also receive an error from the TEAM Engine:
http://cite.opengeospatial.org/teamengine/rest/suites/wfs20/1.26/run?wfs=http://services.cuzk.cz/wfs/inspire-cp-wfs.asp%3FACCEPTVERSIONS%3D2.0.0%26REQUEST%3DGetCapabilities%26SERVICE%3Dwfs%26VERSION%3D2.0.0

Same applies for your complete encoded URL:
http://cite.opengeospatial.org/teamengine/rest/suites/wfs20/1.26/run?wfs=http%3A%2F%2Fservices.cuzk.cz%2Fwfs%2Finspire-cp-wfs.asp%3FACCEPTVERSIONS%3D2.0.0%26request%3DGetCapabilities%26service%3Dwfs%26VERSION%3D2.0.0

I will open an issue in the OGC Team Engine repository.

**Comment by MichalMed** [comment]
Thanks, let me know what happens (if something).

**Comment by cportele** [comment]
A comment on http://services.cuzk.cz/wfs/inspire-cp-wfs.asp%3FACCEPTVERSIONS%3D2.0.0%26REQUEST%3DGetCapabilities%26SERVICE%3Dwfs%26VERSION%3D2.0.0. It is interesting that this URL returns a capabilities document at all. Due to the encoding of the &/?/= characters this is not a valid GetCapabilities URL (there is no query part). But it is incomplete when compared to the correct URL http://services.cuzk.cz/wfs/inspire-cp-wfs.asp?FACCEPTVERSIONS=2.0.0&REQUEST=GetCapabilities&SERVICE=wfs as it missed at least the sections about the feature types and the extended capabilities.

The correct request to the Team Engine would be (as you suggest, Michal) http://cite.opengeospatial.org/teamengine/rest/suites/wfs20/1.26/run?wfs=http%3A%2F%2Fservices.cuzk.cz%2Fwfs%2Finspire-cp-wfs.asp%3FACCEPTVERSIONS%3D2.0.0%26request%3DGetCapabilities%26service%3Dwfs

However, http://cite.opengeospatial.org/teamengine/rest/suites/wfs20/1.26/ states that only the & must be encoded.

I do not think, the issue is related to encoding. If I test the WFS using the Team Engine UI, the test is aborted with an exception "Default CRS not recognized. No transform for classification ?Krovak (North Orientated)?" (we do not see this information via the API).

It seems as the Team Engine is not able to handle the CRS. Michal, you may want to open an issue about this in the OGC CITE issue tracker.

**Comment by MichalMed** [comment]
Hi Clemens, that is really interesting, I thought that OGC validator supports all official EPSG codes (including 5514). I would like to open the issue, but I have not found how. http://cite.opengeospatial.org/issues has no button to add new issue.
Anyway, this has nothing to do with the related issue. I'm handling the changes in encoding with our suppliers now and we'll see if it helps in this case. Could you please help me with opening the issue, please?

**Comment by jonherrmann** [comment]
The repo for the OGC wfs 2.0 tests is here:
https://github.com/opengeospatial/ets-wfs20/issues

**Comment by cportele** [comment]
And the general guidance on how to raise issues is here: https://cite.opengeospatial.org/forum

You can also send an email to the cite-forum mailing list.

**Comment by tb041** [comment]
Testing a standard GeoServer installation result in a similar problem. The unencoded URL is

http://maps.luomus.fi/geoserver/wfs?ACCEPTVERSIONS=2.0.0&REQUEST=GetCapabilities&service=wfs&VERSION=2.0.0

Attempts to encode &'s only and also additional special characters fail:
- No encoding: 'your server does not support URL encoding correctly' and  'exceptionCode="MissingParameterValue" locator="request"'
- &'s encoded as %26's: As with no encoding
- All special characters encoded: "error":"URI \u0027http%3A%2F%2Fmaps.luomus.fi%2Fgeoserver%2Fwfs%3FACCEPTVERSIONS%3D2.0.0%26REQUEST%3DGetCapabilities%26SERVICE%3Dwfs%26VERSION%3D2.0.0\u0027 is not 
absolute"

Am I missing something or is it something that needs fixing elsewhere?

**Comment by jonherrmann** [comment]
@tb041 
There are two issues here. First the validators test driver needs a fix to encode the whole URL and not only the '&' characters.

The second issue is a pending bug in the OGC Team Engine: https://github.com/opengeospatial/ets-wfs20/issues/66 . The Team Engine currently just stops if the default CRS is not supported and reports an ```Error executing test suite (wfs20-1.26)``` to the INSPIRE validator.

A more helpful error message can be obtained by using the OGC Team Engine web interface http://cite.opengeospatial.org/teamengine/.

**Comment by MichalMed** [comment]
Who needs to support default CRS. TEAM Engine, or INSPIRE ETF validator?

**Comment by jonherrmann** [comment]
The INSPIRE validator invokes the TEAM Engine. If you have any suggestion how we could communicate this better in the ETS description

```
This Executable Test Suite is executed using a remote TEAM Engine instance hosted by OGC for their Compliance Program (CITE). The results are transformed into the ETF internal report format. Some information that is typically included in ETF test results is not included in the TEAM Engine reports and cannot be included in this test report.

Please report any issues or problems with the OGC CITE tests in the OGC Compliance Forum.
```

then please feel free to open a new issue.

So the CRS errors are thrown by the OGC Team Engine. In Toms case, the error is thrown because the OGC Team Engine rejects the default CRS with the syntax:

```
<DefaultCRS>http://www.opengis.net/gml/srs/epsg.xml#4326</DefaultCRS>
```

The encoding issue (which actually this ticket addresses) is already fixed -but not yet deployed.

**Comment by MichalMed** [comment]
It looks like it was solved by TeamEngine TestSuite https://github.com/opengeospatial/ets-wfs20/issues/66#issuecomment-418612250, but in the validator, OGC TestSuite won't run due to error: http://inspire-sandbox.jrc.ec.europa.eu/etf-webapp/v2/TestRuns/EIDe4f4858d-0daa-4dda-beab-58dcd6cc5010.html

Is this on ETF or CITE side?

**Comment by jonherrmann** [comment]
Michal, the issue is [still](https://github.com/opengeospatial/ets-wfs20/issues/66) open in the OGC repository. And the Pull Request merge is [still](https://github.com/opengeospatial/ets-wfs20/pull/127) pending. And the milestone of the issue is set to '[Due by October 31, 2018](https://github.com/opengeospatial/ets-wfs20/milestone/9)'. I think it may take a while for the new CITE test to be available :)

**Comment by MichalMed** [comment]
Jon, issue is closed and error remains. http://inspire-sandbox.jrc.ec.europa.eu/etf-webapp/v2/TestRuns/EID2a72f249-2871-4512-a344-ff385a933cd6.html
Is validator using newest version of CITE?

**Comment by jonherrmann** [comment]
Hi Michal, by default ETF tries to use the latest version of the public CITE instance.

The public instance still doesn't seem to have received the update, as it still returns version 1.26. The milestone 1.31 with the bugfix is closed but it seems that OGC still has not release+deployed it yet.

This Version can be checked by visiting this site:
http://cite.opengeospatial.org/teamengine/rest/suites/
and clicking on **WFS 2.0 (ISO 19142:2010) Conformance Test Suite**. The last segment of the URL in the Browser will tell you the version.
